### PR TITLE
Feature/standalone config generation

### PR DESCRIPTION
**Pull request by lrascao**
This set of commits will bring `cuttlefish` to a point where i'm able to invoke:

`cuttlefish --etc_dir etc --dest_dir output_dir --dest_file generated.config --schema_dir path_to/schemas --conf_file etc/a_conf_file.conf --allow_extra --silent`

This invocation will look in `path_to/schemas`, find all `.schema` files and generate a single .config file to `output_dir/generate.config` based on values expressed in `etc/a_conf_file.conf`.

In my particular use case i'm not interested in generating `vm.args` or a full fledged `sys.config` file. I only want to take advantage of cuttlefish's schema/conf functionality to generate a single tuple-based .config file.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@lrascao @lukebakken I like this idea

**Comment by lrascao** [comment]
ping, is this missing something or just not enough bandwidth atm?

**Comment by lukebakken** [comment]
@lrascao please remember that this free, open source software is maintained by volunteers.

**Comment by lrascao** [comment]
i understand that completely as i maintain a few of my own, wasn't my intention to put anyone under pressure, just wondering if this had slipped under the radar, now i know it's not

**Comment by lrascao** [comment]
i've rebased onto master for a cleaner history

**Review by lukebakken — APPROVED** [review]

**Comment by lukebakken** [comment]
Thank you!

**Comment by lrascao** [comment]
thanks! i've got another one in the pipe that is in the same vein, but for vm.args, maybe hold off a bit on `2.5.0` until i put that forward

**Pull request merged**
