### PR TITLE
Add new domain_socket data type

### PR DESCRIPTION
**Pull request by codeadict**
Adds `domain_socket` as a new datatype, separate from the existing `ip` but with the convenience of parsing "local:/path/to/your.sock:0" or "unix:/path/to/your.sock:0" into {local, "/path/to/your.sock",  0} , following the type at https://www.erlang.org/doc/man/inet.html#type-local_address.

### CODE REVIEW

**Comment by codeadict** [comment]
Thanks @ioolkos, pinging @michaelklishin @lukebakken for visibility.

**Comment by michaelklishin** [comment]
Something is off with Erlang provisioning on Actions.

I don't have any objections to adding this new data type.

**Comment by codeadict** [comment]
Thanks, i know wbat the GHA problem is, going to fix it here

**Comment by lukebakken** [comment]
@codeadict thanks for pinging me. I didn't get or didn't notice an email about this PR.

**Comment by codeadict** [comment]
Awesome @lukebakken , you can give a shot now to running the Github actions 🤞🏽

**Review by lukebakken — APPROVED** [review]
@codeadict some of the quoting changes in the GHA workflow file were invalid. I like single quotes anyway 😉 Waiting for GHA to finish then I'll merge.

PS I cherry-picked your changes into https://github.com/Kyorai/cuttlefish/pull/34

**Review by lukebakken — CHANGES_REQUESTED** [review]
Looks like dialyzer failed:

```
src/cuttlefish_datatypes.erl
Line 332 Column 1: The pattern <String, _UDSStr, _, 'undefined'> can never match the type <string(),string(),{'match',nonempty_string()},0>
===> Warnings written to _build/default/25.2.2.dialyzer_warnings
===> Warnings occurred running dialyzer: 1
```

**Comment by codeadict** [comment]
Thanks @lukebakken . Yeah no hard opinion on the quotes, my editor as changing them all the time on save to double quotes but i just figured it was the prettier extension I had enabled.

**Comment by codeadict** [comment]
🎉

**Comment by lukebakken** [comment]
@ioolkos @codeadict here you go!

https://github.com/Kyorai/cuttlefish/releases/tag/v3.2.0

THANKS!

**Comment by lukebakken** [comment]
https://hex.pm/packages/cuttlefish/3.2.0

**Comment by ioolkos** [comment]
Yay, thanks @lukebakken! :)

**Comment by codeadict** [comment]
Thanks a lot. cheers!

**Pull request merged**
